export const LOAD_BROKERS_SUCCESS = 'LOAD_BROKERS_SUCCESS';
export const LOAD_HOBBIES_SUCCESS = 'LOAD_HOBBIES_SUCCESS';
export const UPDATE_BROKER_SUCCESS = 'UPDATE_BROKER_SUCCESS';
export const CREATE_BROKER_SUCCESS = 'CREATE_BROKER_SUCCESS';
export const DELETE_BROKER_SUCCESS = 'DELETE_BROKER_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';